export const fallbackProjects = [
  {
    id: 'sim',
    title: 'S_im',
    description: 'Shadow Simulator',
    category: 'Software',
    status: 'In Progress',
    technology: ['Simulation', 'Software'],
    tags: ['simulation', 'software', 'development'],
    route: '/projects/sim',
    dateCreated: '2024-01-01',
  },
  {
    id: 'sos',
    title: 'sOS',
    description: 'Shadow Operating System',
    category: 'Software',
    status: 'In Progress',
    technology: ['Operating System', 'Low-level'],
    tags: ['os', 'system', 'low-level', 'kernel'],
    route: '/projects/sos',
    dateCreated: '2023-06-15',
  },
  {
    id: 's9',
    title: 'S9',
    description: 'Shadow Home Server',
    category: 'Hardware',
    status: 'Active',
    technology: ['Server', 'Networking', 'Linux'],
    tags: ['server', 'networking', 'nas', 'ubuntu', 'homelab'],
    route: '/projects/s9',
    dateCreated: '2024-10-01',
  },
  {
    id: 'nfi',
    title: 'NFI',
    description: 'Rocket Propulsion System',
    category: 'Hardware',
    status: 'Completed',
    technology: ['Aerospace', 'Engineering'],
    tags: ['rocket', 'propulsion', 'aerospace', 'engineering'],
    route: '/projects/NFI',
    dateCreated: '2022-03-01',
  },
  {
    id: 'muse',
    title: 'Muse',
    description: 'Automated Audio Equalizer',
    category: 'Hardware',
    status: 'Discontinued',
    technology: ['Audio', 'Electronics'],
    tags: ['audio', 'music', 'equalizer', 'electronics'],
    route: '/projects/muse',
    dateCreated: '2018-03-01',
  },
  {
    id: 'el',
    title: 'EyeLearn',
    description: 'Academia AR/VR Headset',
    category: 'Hardware',
    status: 'Paused',
    technology: ['AR/VR', 'Education'],
    tags: ['ar', 'vr', 'education', 'headset', 'learning'],
    route: '/projects/EL',
    dateCreated: '2021-09-01',
  },
  {
    id: 'naton',
    title: 'Naton',
    description: 'Element Converter',
    category: 'Hardware',
    status: 'Completed',
    technology: ['Chemistry', 'Physics'],
    tags: ['chemistry', 'physics', 'converter', 'elements'],
    route: '/projects/Naton',
    dateCreated: '2020-01-15',
  },
];

export default fallbackProjects;
